In [190]:
# Импортируем объект Counter из модуля collections
from collections import Counter
# Создаём пустой объект Counter
c = Counter()

c['red'] += 1
print(c)

# Будет напечатано:
# Counter({'red': 1})

cars = ['red', 'blue', 'black', 'black', 'black', 'red', 'blue', 'red', 'white']



Counter({'red': 1})


Посчитать значения, конечно, можно и в цикле, используя синтаксис из предыдущего примера:

In [191]:
c = Counter()
for car in cars:
    c[car] += 1
    
print(c)

Counter({'red': 3, 'black': 3, 'blue': 2, 'white': 1})


Однако гораздо проще при создании Counter сразу передать в круглых скобках итерируемый объект, в котором необходимо посчитать значения:

In [192]:
c = Counter(cars)
print(c)
print(c['black'])

Counter({'red': 3, 'black': 3, 'blue': 2, 'white': 1})
3


Несуществующий ключ в счётчике
возвращает 0, так как такого элемента нет( встречается 0 раз)

In [193]:
print(c['purple'])


0


In [194]:
print(c.values())
print(c.keys())
print(sum(c.values()))
print()

dict_values([3, 2, 3, 1])
dict_keys(['red', 'blue', 'black', 'white'])
9



В этой конструкции мы сначала получаем элементы (число раз, когда встретился ключ) с помощью функции values (такая же функция есть и у словаря):

print(c.values())
# dict_values([3, 2, 3, 1])

Затем суммируем полученные значения итерируемого объекта dict_values, который выглядит почти как список, с помощью встроенной функции sum.

Операции с Counter

Возможности Counter не ограничиваются только подсчётом элементов. Этот объект обладает и дополнительным функционалом — например, счётчики можно складывать и вычитать.

In [195]:
cars_moscow = ['black', 'black', 'white', 'black', 'black', 'white', 'yellow', 'yellow', 'yellow']
cars_spb = ['red', 'black', 'black', 'white', 'white', 'yellow', 'yellow', 'red', 'white']

counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)

print(counter_moscow)
print(counter_spb)

#Сложение
print('sum', counter_moscow + counter_spb)

#Вычитание
print()
print('subtract')
counter_moscow.subtract(counter_spb)
print(counter_moscow)

Counter({'black': 4, 'yellow': 3, 'white': 2})
Counter({'white': 3, 'red': 2, 'black': 2, 'yellow': 2})
sum Counter({'black': 6, 'white': 5, 'yellow': 5, 'red': 2})

subtract
Counter({'black': 2, 'yellow': 1, 'white': -1, 'red': -2})


функцию subtract не всегда бывает удобно использовать для вычитания, так как модифицируется исходный счётчик. Однако аналога у этой функции нет, поскольку вычитание с помощью оператора "-" приводит к другому результату:

In [196]:
#Счётчики надо пересоздать так как subtract модифицирует оригинальный объект
counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)
# print(counter_moscow)
# print(counter_spb)
print(counter_moscow - counter_spb)
# В данном случае нет значений меньше 1, поэтому нет данных о разнице в числе белых и красных машин.


Counter({'black': 2, 'yellow': 1})


#Дополнительные функции

In [159]:
counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)

Чтобы получить список всех элементов, которые содержатся в Counter, используется функция elements(). Она возвращает итератор, поэтому, чтобы напечатать все элементы, распакуем их с помощью *:

In [160]:
print (*counter_moscow.elements())
#elements() функция
# * - Распаковщик
print (counter_moscow.elements())

black black black black white white yellow yellow yellow


Обратите внимание, что элементы возвращаются в порядке появления уникальных элементов. Например, элемент “black” встречается в списке cars_moscow первым, элемент “white” вторым, а элемент “yellow” третьим. Соответственно, в этом же порядке будут выведены элементы Counter().

 Чтобы получить список уникальных элементов, достаточно воспользоваться функцией list():

In [161]:
print(list(counter_moscow))
print(len(list(counter_moscow)))

['black', 'white', 'yellow']
3


С помощью функции dict() можно превратить Counter в обычный словарь:

In [162]:
print(counter_moscow)
print(dict(counter_moscow))
print(counter_moscow)

Counter({'black': 4, 'yellow': 3, 'white': 2})
{'black': 4, 'white': 2, 'yellow': 3}
Counter({'black': 4, 'yellow': 3, 'white': 2})


In [163]:
type(counter_moscow)

collections.Counter

Функция most_common() позволяет получить список из кортежей элементов в порядке убывания их встречаемости:

In [164]:
print(counter_moscow.most_common())
print(counter_moscow.most_common(2))

[('black', 4), ('yellow', 3), ('white', 2)]
[('black', 4), ('yellow', 3)]


Наконец, функция clear() позволяет полностью обнулить счётчик:

In [165]:
counter_moscow.clear()
print(counter_moscow)
counter_moscow = Counter(cars_moscow)
print(counter_moscow)

Counter()
Counter({'black': 4, 'yellow': 3, 'white': 2})


**Defaultdict**

In [166]:
students = [('Ivanov',1),('Smirnov',4),('Petrov',3),('Kuznetsova',1),
            ('Nikitina',2),('Markov',3),('Pavlov',2)]
#список из кортежей с фамилиями и учебнымигруппами



Сохраним эти данные в словаре, в котором ключами будут номера групп, а элементами — списки студентов. Сделать это можно следующим образом:

In [167]:
students = [('Ivanov',1),('Smirnov',4),('Petrov',3),('Kuznetsova',1),
            ('Nikitina',2),('Markov',3),('Pavlov',2)]
#список из кортежей с фамилиями и учебнымигруппами

groups = dict()

for student, group in students:
    # Проверяем, есть ли уже эта группа в словаре
    if group not in groups:
         # Если группы ещё нет в словаре, создаём для неё пустой список
         groups[group] = list()
         print(groups)
    groups[group].append(student)
    
print(groups)
# {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']}
        

{1: []}
{1: ['Ivanov'], 4: []}
{1: ['Ivanov'], 4: ['Smirnov'], 3: []}
{1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov'], 2: []}
{1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']}


В данном коде в цикле for происходит распаковка кортежа: в переменные цикла student и group попадают первый и второй элементы кортежей из списка students. То есть на первой итерации цикла в переменной student содержится строка 'Ivanov', а в переменной group — целое число 1. На второй итерации цикла в переменной student содержится строка 'Smirnov', а в переменной group — целое число 4. И так далее.

Обратите внимание, что для решения этой задачи нам потребовался шаг с проверкой наличия номера группы в словаре. Если номера группы не было, для этой группы мы создавали новый список в словаре. Без шага проверки мы бы натолкнулись на KeyError:

In [168]:

# groups = dict()

# for student, group in students:
#     groups[group].append(student)
    
# print(groups)

Данная ошибка означает, что ключа 1 нет в словаре.

Например, чтобы сохранить информацию о колебании курсов валют за последний месяц, можно создать словарь из валютных пар (USD/RUB, EUR/RUB и т. д.), а по ключам разместить списки из стоимости валюты по курсу ЦБ за последние 30 дней. В таком словаре по каждому ключу должен быть доступен список.

Создадим defaultdict, в котором при обращении по несуществующему ключу будет автоматически создаваться новый список. Для этого при создании объекта defaultdict в круглых скобках передадим параметр list:

In [169]:
from collections import defaultdict
groups = defaultdict(list) 
# Обратите внимание, что в скобках мы передаём именно указатель на класс объекта (например list; 
# также можно было бы применить set, dict) без круглых скобок, которые используются для создания нового экземпляра объекта.

In [170]:
groups.clear()
for student, group in students:
    groups[group].append(student)
    print(groups)
    
print()
print(groups)

defaultdict(<class 'list'>, {1: ['Ivanov']})
defaultdict(<class 'list'>, {1: ['Ivanov'], 4: ['Smirnov']})
defaultdict(<class 'list'>, {1: ['Ivanov'], 4: ['Smirnov'], 3: ['Petrov']})
defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov']})
defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov'], 2: ['Nikitina']})
defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina']})
defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']})

defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']})


Получить элемент из defaultdict по ключу можно так же, как и из обычного словаря:

In [171]:
print(groups[3])

['Petrov', 'Markov']


Если запрашиваемого ключа нет в словаре, KeyError не возникнет. Вместо этого будет напечатан пустой элемент, который создаётся в словаре по умолчанию:

In [172]:
print(groups[29])
print(groups[88])
print(groups[88])

[]
[]
[]


Теперь в словаре groups автоматически появился элемент 29 и 88 с пустым списком внутри, несмотря на то что мы его не создавали:

In [173]:
print(groups)

defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov'], 29: [], 88: []})


In [174]:
dict_object = dict()
defaultdict_object = defaultdict()

print(type(dict_object))
print(type(defaultdict_object))

<class 'dict'>
<class 'collections.defaultdict'>


In [175]:
print(dict_object)
print(defaultdict_object)
# Заметьте, что в этом примере мы не задавали объект, 
# который по умолчанию хранится в экземпляре defaultdict, 
# поэтому объектом по умолчанию является None.

{}
defaultdict(None, {})


3. Модуль Collections. Deque и OrderedDict

**OrderedDict**

In [176]:
import sys
print(sys.version)
data = [('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)]
client_ages = dict(data)
print(client_ages)


3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
{'Ivan': 19, 'Mark': 25, 'Andrey': 23, 'Maria': 20}


Специальный словарь, который гарантирует сохранение ключей в порядке их добавления, называется OrderedDict:
В Python 3.7 и дальше обычные словари тоже сохраняют порядок

In [177]:
from collections import OrderedDict
data = [('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)]
ordered_client_ages = OrderedDict(data)
print(ordered_client_ages)

# Если теперь добавить нового человека в словарь, новая запись окажется в конце:
ordered_client_ages['Nikita'] = 18
print(ordered_client_ages)

# Если удалить элемент, а затем добавить его снова, он также окажется в конце:
del ordered_client_ages['Andrey']
print(ordered_client_ages)
ordered_client_ages['Andrey'] = 23
print(ordered_client_ages)


OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])
OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20), ('Nikita', 18)])
OrderedDict([('Ivan', 19), ('Mark', 25), ('Maria', 20), ('Nikita', 18)])
OrderedDict([('Ivan', 19), ('Mark', 25), ('Maria', 20), ('Nikita', 18), ('Andrey', 23)])


Можно, например, отсортировать с помощью функции sorted список кортежей при создании из него OrderedDict, и объекты будут добавлены в порядке сортировки:

In [178]:
data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]

ordered_dict_ages = OrderedDict(sorted(data, key=lambda x: x[1]))
print(client_ages)

{'Ivan': 19, 'Mark': 25, 'Andrey': 23, 'Maria': 20}


Deque

Double-ended queue — двухконцевая очередь). Она объединяет в себе возможности и стека, и очереди: содержит функции, которые позволяют добавлять элементы в начало или в конец очереди, а также извлекать первый или последний элемент из неё. 
Можно сказать, что стек и очередь — это принципы обработки данных. deque позволяет обрабатывать данные обоими способами в зависимости от того, что требуется от разработчика. В каком порядке обрабатывать данные (FIFO или LIFO) вам подскажет собственная логика или более продвинутая теория алгоритмов, которая в данном модуле не изучается.

У deque есть четыре ключевые функции:

        append (добавить элемент в конец дека);
        appendleft (добавить элемент в начало дека);
        pop (удалить и вернуть элемент из конца дека);
        popleft (удалить и вернуть элемент из начала дека).
        extend добавить в конец дека несколько элементов
        extendleft (добавить в начало дека).


In [179]:
from collections import deque
dq = deque()
print(dq)

deque([])


clients.append('Ivanov')
clients.append('')

In [180]:
clients = deque()
clients.append('Ivanov')
clients.append('Petrov')
clients.append('Smirnov')
clients.append('Tikhonova')
print(clients)


deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])


In [181]:
# Объект deque поддерживает индексацию по элементам:
clients = deque()
clients.append('Ivanov')
clients.append('Petrov')
clients.append('Smirnov')
clients.append('Tikhonova')
print('clients:', clients)

first_client = clients.popleft()
second_client = clients.popleft()
#third_client = clients.popleft()

print('First client:', first_client)
print('Second client:', second_client)
print(clients)


clients.appendleft('VIP')
print(clients)

tired_client = clients.pop()
print('tired client:', tired_client)
print(clients)

clients: deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])
First client: Ivanov
Second client: Petrov
deque(['Smirnov', 'Tikhonova'])
deque(['VIP', 'Smirnov', 'Tikhonova'])
tired client: Tikhonova
deque(['VIP', 'Smirnov'])


In [182]:
clients = deque(['Ivanov', 'Petrov', 'Srmirnov', 'Tikhonova'])
print(clients)
del clients[2]
print(clients)

deque(['Ivanov', 'Petrov', 'Srmirnov', 'Tikhonova'])
deque(['Ivanov', 'Petrov', 'Tikhonova'])


In [183]:
shop = deque([1, 2, 3, 4, 5])
print(shop)
shop.extend([11, 12, 13, 14, 15])
print(shop)
shop.extendleft([16, 17, 18, 19, 20])
print(shop)


deque([1, 2, 3, 4, 5])
deque([1, 2, 3, 4, 5, 11, 12, 13, 14, 15])
deque([20, 19, 18, 17, 16, 1, 2, 3, 4, 5, 11, 12, 13, 14, 15])


Обратите внимание, что «клиенты из автобуса» оказались в очереди не в том порядке, в каком они «выходили из автобуса». То есть добавленные номера не только приписаны перед записанными в очереди номерами, но также порядок добавленных элементов поменялся на обратный. Это связано с тем, что действие функции extendleft аналогично многократному применению функции appendleft, поэтому самый последний клиент из автобуса оказался в итоге первым в очереди.

            Очередь с ограниченной максимальной длиной

При создании очереди можно также указать её максимальную длину с помощью параметра maxlen. Сделать это можно как при создании пустой очереди, так и при создании очереди от заданного итерируемого объекта:

In [184]:
limited = deque(maxlen =3)
print(limited) # макс длина дека тоже печатается

limited_from_list = deque([1,2,3,4,5,6,7], maxlen=3)
print(limited_from_list) # в очереди с ограниченной длиной сохраняются только последние элементы, а первые исчезают из памяти:

limited.extend([1,2,3])
print(limited)

print(limited.append(8))
print(limited)

limited.append(9)
print(limited)


deque([], maxlen=3)
deque([5, 6, 7], maxlen=3)
deque([1, 2, 3], maxlen=3)
None
deque([2, 3, 8], maxlen=3)
deque([3, 8, 9], maxlen=3)


При этом, как видно из результата операции limited.append(8), удаляемый элемент не возвращается, а просто исчезает.

?
Для чего может пригодиться такая возможность?

Например, необходимость в таком инструменте возникает, когда за один раз необходимо обрабатывать строго фиксированное число элементов. Особенно это актуально для анализа динамики какого-то значения во времени.

Посчитаем динамику средней температуры с усреднением за каждые последние 7 дней для каждого рассматриваемого дня. Для этого воспользуемся очередью с параметром maxlen=7:

In [185]:
temps = [20.6, 19.4, 19.0, 19.0, 22.1,
        22.5, 22.8, 24.1, 25.6, 27.0,
        27.0, 25.6, 26.8, 27.3, 22.5,
        25.4, 24.4, 23.7, 23.6, 22.6,
        20.4, 17.9, 17.3, 17.3, 18.1,
        20.1, 22.2, 19.8, 21.3, 21.3,
        21.9]

days = deque(maxlen=7)

for temp in temps:
    # Добавляем температуру в очередь
    days.append(temp)
    # Если длина очереди оказалась равной максимальной длине очереди (7),
    # печатаем среднюю температуру за последние 7 дней
    if len(days) == days.maxlen:
        print(round(sum(days) / len(days), 2), end='; ')
# Напечатаем пустую строку, чтобы завершить действие параметра
# end. Иначе следующая строка окажется напечатанной на предыдущей
print("")

20.77; 21.27; 22.16; 23.3; 24.44; 24.94; 25.56; 26.2; 25.97; 25.94; 25.57; 25.1; 24.81; 24.21; 23.23; 22.57; 21.41; 20.4; 19.6; 19.1; 19.04; 18.96; 19.44; 20.01; 20.67; 


Дополнительные функции

        # reverse позволяет поменять порядок элементов в очереди на обратный:
        rotate переносит заданных элементов из конца очереди в начало:
        Функция index позволяет найти первый индекс искомого элемента
        count позволяет подсчитать, сколько раз элемент встретился в очереди (функции аналогичны одноимённым функциям для списков):
        функция clear позволяет очистить очередь:

In [186]:
# reverse позволяет поменять порядок элементов в очереди на обратный:
print('--- reverse-----')
dq = deque([1,2,3,4,5])
print(dq)

 
dq.reverse()
print(dq)
print()




--- reverse-----
deque([1, 2, 3, 4, 5])
deque([5, 4, 3, 2, 1])



In [187]:
# rotate переносит заданных элементов из конца очереди в начало:
print('---- rotate ----')
dq = deque([1,2,3,4,5])
print(dq)

dq.rotate(2) # считает с конца, 1й = 5, 2й = 4. Цифра указывает количество элементов
print(dq)

# Элементы можно переносить и из начала в конец:

dq = deque([1,2,3,4,5])
print(dq)

dq.rotate(-2)
print(dq)

# Обратите внимание, что порядок внутри перенесённых элементов остался тем же, каким был изначально. 
# Вспомните, в каком порядке добавляются элементы в начало очереди функцией extend, и сопоставьте с действием rotate.
print()



---- rotate ----
deque([1, 2, 3, 4, 5])
deque([4, 5, 1, 2, 3])
deque([1, 2, 3, 4, 5])
deque([3, 4, 5, 1, 2])



In [188]:

print('---- index,  count ----')
dq = [1,2,4,2,3,1,5,4,4,4,4,4,3]
print(dq.index(4))
dq.index(4) 
print(dq.count(4))
dq.count(4)


---- index,  count ----
2
6


6

In [189]:
#  при попытке узнать индекс несуществующего элемента возникнет ValueError:
dq = deque([1,2,4,2,3,1,5,4,4,4,4,4,3])
print(dq.index(25))

ValueError: 25 is not in deque

In [ ]:
# А вот посчитать несуществующий элемент можно (получится просто 0):
dq = deque([1,2,4,2,3,1,5,4,4,4,4,4,3])
print(dq.count(25))

0


In [ ]:
dq = deque([1,2,4,2,3,1,5,4,4,4,4,4,3])
print(dq)
dq.clear()
print(dq)


deque([1, 2, 4, 2, 3, 1, 5, 4, 4, 4, 4, 4, 3])
deque([])


##Закрепление

Напишите функцию brackets(line), которая определяет, является ли последовательность из круглых скобок правильной.
Какая последовательность скобок правильная?

Правильной скобочной последовательностью назовём такую последовательность скобок, в которой для каждой открывающей скобки есть последующая соответствующая ей закрывающая скобка.

Цветом обозначены соответствующие друг другу скобки: (()())()

Соответственно, остальные скобочные последовательности назовём неправильными.

Пустую строку будем считать правильной последовательностью.

Для решения этой задачи потребуется использовать стек.

Посимвольно переберите строку. Если встретилась открывающаяся скобка, положите её в стек. Если встретилась закрывающаяся скобка, извлеките скобку из стека.

        Если стек пустой, то есть извлечь скобку нельзя, последовательность неправильная.
        Если строка закончилась и стек стал пустым, последовательность правильная.
        Если в стеке остались скобки, последовательность неправильная.

Пример:

In [ ]:
from collections import deque

def brackets(line):
    stack = deque()
    for i in line:
        if i=='(':
            stack.append(i)
        elif i ==')':
            if len(stack) == 0:
                return False
            stack.pop()
    if len(stack) == 0:
        return True
    return False

print(brackets("(()())"))
# True
print(brackets(""))
# True
print(brackets("(()()))"))
# False

True
True
False


В переменных center, south и north хранятся списки из перечней купленных позиций в трёх торговых точках, расположенных в разных районах города.

Вначале избавьтесь от излишней вложенности: в каждой переменной (center, south, north) должен храниться объединённый список купленных товаров без разбиения по чекам.

Пример: [['Milk', 'Bread'], ['Meat']] -> ['Milk', 'Bread', 'Meat']

In [ ]:

list_north = [elem for bill in north for elem in bill]
list_center = [elem for bill in center for elem in bill]
list_south = [elem for bill in south for elem in bill]
print(len(list_north))
print(len(list_center))
print(len(list_south))

Теперь получите объекты-счётчики (Counter) из каждого полученного в предыдущем задании списка покупок и сохраните их в отдельные переменные (они пригодятся для выполнения следующих задач).

Сколько раз покупали самый редкий товар в магазине north? Запишите ответ в числовой форме.

In [ ]:
from collections import Counter

list_north = [elem for bill in north for elem in bill]
list_center = [elem for bill in center for elem in bill]
list_south = [elem for bill in south for elem in bill]
print(len(list_north))
print(len(list_center))
print(len(list_south))

c_north = Counter(list_north)
c_center = Counter(list_center)
c_south = Counter(list_south)

print(c_north)
print(c_north.most_common()[-1])

 Задание 4.7
Есть ли такой товар, который в одном из магазинов покупали чаще, чем в двух других вместе взятых? Если да, выберите магазин с настолько популярным товаром:

 Задание 4.8
Определите суммарное число продаж каждого товара во всех магазинах, сложив все объекты-счётчики. Сколько раз был куплен второй по популярности товар? Запишите ответ в числовой форме.

In [ ]:
from collections import Counter

list_north = [elem for bill in north for elem in bill]
list_center = [elem for bill in center for elem in bill]
list_south = [elem for bill in south for elem in bill]
print(len(list_north))
print(len(list_center))
print(len(list_south))

c_north = Counter(list_north)
c_center = Counter(list_center)
c_south = Counter(list_south)

print(c_north)
print(c_center)
print(c_north.most_common()[-1])
print(c_center - c_north)
print()
print (c_north - (c_center + c_south))
print (c_center - (c_north + c_south))
print (c_south - (c_center + c_north))
# c_center.subtract(c_north)
print(c_center)
total = c_north + c_center + c_south
print(total)
print(total.most_common()[1])

Дан список кортежей ratings с рейтингами кафе. Кортеж состоит из названия и рейтинга кафе.

Необходимо отсортировать список кортежей по убыванию рейтинга. Если рейтинги совпадают, то отсортировать кафе дополнительно по названию в алфавитном порядке.

Получите словарь cafes с упорядоченными ключами из отсортированного списка, где ключи — названия кафе, а значения — их рейтинг.

In [ ]:
from collections import OrderedDict
ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8),
           ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1),
           ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]


ratings.sort(key=lambda x:( -x[1], x[0]))
# print(ratings)

cafes = OrderedDict(ratings)
# print(cafes)

In [ ]:
ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8),
           ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1),
           ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]


ratings.sort(key=lambda x: (x[0])) # отсортирует по алфавиту
print('1', ratings)

ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]
ratings.sort(key=lambda x: (x[0], -x[1])) # отсортирует по алфавиту как и предыдущий
print('2', ratings)

ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]
ratings.sort(key=lambda x: (-x[1])) # отсортирует по рейтингу, но не по алфавиту
print('3',ratings)

ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]
ratings.sort(key=lambda x: (x[1])) # отсортирует по рейтингу с низкого, игнорируя алфавит
print('a',ratings)

# ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]
# ratings.sort(key=lambda x: (-x[1], x[0])) # отсортирует по рейтингу И по алфавиту
# print('4',ratings)

ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]
ratings.sort(key=lambda x: (x[1], x[0])) # отсортирует по рейтингу с низкого
print('5',ratings)

ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]
ratings.sort(key=lambda x: (x[1], -x[1])) # отсортирует 
print('6',ratings)

ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]
ratings.sort(key=lambda x: (-x[1], x[0])) # отсортирует по рейтингу И по алфавиту
print('7',ratings)

ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]
ratings.sort() # отсортирует по алфавиту
print('8',ratings)

# ratings.sort(key=lambda x: (-x[1], x[0]))
# print(ratings)
# ratings.sort() # отсортирует по алфавиту
# print(ratings)
# ratings.sort(key=lambda x: (x[0], -x[1])) # отсортирует по алфавиту
# print(ratings)

1 [('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('General Foods', 4.8), ('New Age', 4.6), ('Nice Cakes', 3.9), ('Old Gold', 3.3), ('Old Wine Cellar', 3.3), ('Old York', 3.3), ('WokAndRice', 4.9), ('WokToWork', 4.9)]
2 [('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('General Foods', 4.8), ('New Age', 4.6), ('Nice Cakes', 3.9), ('Old Gold', 3.3), ('Old Wine Cellar', 3.3), ('Old York', 3.3), ('WokAndRice', 4.9), ('WokToWork', 4.9)]
3 [('WokToWork', 4.9), ('WokAndRice', 4.9), ('General Foods', 4.8), ('New Age', 4.6), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('Nice Cakes', 3.9), ('Old York', 3.3), ('Old Gold', 3.3), ('Old Wine Cellar', 3.3)]
a [('Old York', 3.3), ('Old Gold', 3.3), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9), ('CakeTime', 4.1), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('Belissimo', 4.5), ('New Age', 4.6), ('General Foods', 4.8), ('WokToWork', 4.9), (

https://pythonru.com/osnovy/vse-chto-nuzhno-znat-o-lambda-funkcijah-v-python

Лямбда-функция и сортировка списков

Сортировка списка — базовая операция в Python. Если речь идет о списке чисел или строк, то процесс максимально простой. Подойдут встроенные функции sort и sorted.

Но иногда имеется список кастомных объектов, сортировать которые нужно на основе значений одного из полей. В таком случае можно передать параметр key в sort или sorted. Он и будет являться функцией.

Функция применяется ко всем элементам объекта, а возвращаемое значение — то, на основе чего выполнится сортировка. Рассмотрим пример. Есть класс Employee.

class Employee:
    def __init__(self, name, age):
        self.name = name
        self.age = age

Теперь создадим экземпляры этого класса и добавим их в список.

Alex = Employee('Alex', 20)
Amanda = Employee('Amanda', 30)
David = Employee('David', 15)
L = [Alex, Amanda, David]

Предположим, что мы хотим отсортировать его на основе поля age сотрудников. Вот что нужно сделать для этого:

L.sort(key=lambda x: x.age)
print([item.name for item in L])
# вывод: ['David', 'Alex', 'Amanda']

Лямбда-выражение было использовано в качестве параметра key вместо отдельного ее определения и затем передачи в функцию sort.

In [ ]:
class Employee:
    def __init__(self, name, age):
        self.name = name
        self.age = age

Alex = Employee('Alex', 20)
Amanda = Employee('Amanda', 30)
David = Employee('David', 15)
L = [Alex, Amanda, David]

L.sort(key=lambda x: x.age)
print([item.name for item in L])
# вывод: ['David', 'Alex', 'Amanda']


['David', 'Alex', 'Amanda']


Напишите функцию task_manager, которая принимает список задач для нескольких серверов. Каждый элемент списка состоит из кортежа (<номер задачи>, <название сервера>, <высокий приоритет задачи>).

Функция должна создавать словарь и заполнять его задачами по следующему принципу: название сервера — ключ, по которому хранится очередь задач для конкретного сервера. Если поступает задача без высокого приоритета (последний элемент кортежа — False), добавить номер задачи в конец очереди. Если приоритет высокий, добавить номер в начало.

Для словаря используйте defaultdict, для очереди — deque.

Функция возвращает полученный словарь с задачами.

Пример:

In [ ]:
from collections import defaultdict, deque

tasks = [(36871, 'office', False),
(40690, 'office', False),
(35364, 'voltage', False),
(41667, 'voltage', True),
(33850, 'office', False)]

def task_manager(tasks):
    servers = defaultdict(deque)
    for task in tasks:
        print('High Prio:',task[-1],',','Server:',task[1],', Number:',task[0])
            
        if task[-1]: # if the last[-1] element is True
            # print('T')                    
            servers[task[1]].appendleft(task[0]) # to the 
            print('T servers:',servers[task[1]]) 
        else:
            # print('F')                  
            servers[task[1]].append(task[0])
            print('F servers:',servers[task[1]])  
    return servers
    


 
print(task_manager(tasks))
# defaultdict(, {'voltage': deque([41667, 35364]),
# 'office': deque([36871, 40690, 33850])})

High Prio: False , Server: office , Number: 36871
F servers: deque([36871])
High Prio: False , Server: office , Number: 40690
F servers: deque([36871, 40690])
High Prio: False , Server: voltage , Number: 35364
F servers: deque([35364])
High Prio: True , Server: voltage , Number: 41667
T servers: deque([41667, 35364])
High Prio: False , Server: office , Number: 33850
F servers: deque([36871, 40690, 33850])
defaultdict(<class 'collections.deque'>, {'office': deque([36871, 40690, 33850]), 'voltage': deque([41667, 35364])})


In [ ]:
tasks = [(36871, 'office', False),
(40690, 'office', False),
(35364, 'voltage', False),
(41667, 'voltage', True),
(33850, 'office', False)]

print(task_manager(tasks))
# defaultdict(, {'voltage': deque([41667, 35364]),
# 'office': deque([36871, 40690, 33850])})


High Prio: False , Server: office , Number: 36871
F servers: deque([36871])
High Prio: False , Server: office , Number: 40690
F servers: deque([36871, 40690])
High Prio: False , Server: voltage , Number: 35364
F servers: deque([35364])
High Prio: True , Server: voltage , Number: 41667
T servers: deque([41667, 35364])
High Prio: False , Server: office , Number: 33850
F servers: deque([36871, 40690, 33850])
defaultdict(<class 'collections.deque'>, {'office': deque([36871, 40690, 33850]), 'voltage': deque([41667, 35364])})


# NumPy


In [ ]:
import numpy as np
np.iinfo(np.int64)
b = np.uint8(124)
print(type(b))

print(2**128)

<class 'numpy.uint8'>
340282366920938463463374607431768211456


Это тип данных с общим корнем int. Int может быть со следующими окончаниями: int8, int16, int32 и int64. Окончание типа данных в NumPy показывает, сколько битов памяти должно быть выделено для хранения переменной.

В NumPy доступны и беззнаковые целочисленные типы данных. Они имеют корень uint (unsigned int — беззнаковое целое). uint доступны также с выделением памяти в 8, 16, 32 и 64 бита. При этом максимально возможное число оказывается в два раза больше, чем для соответствующего int, поскольку отрицательные числа исключены из типа данных uint.

Тип данных не сохранится, если просто присвоить переменной с заданным NumPy-типом данных новое значение:

In [ ]:
a = np.int32(1000)
print(a)
print(type(a))
a = 1001
print(type(a))

a = np.int32(1001)
print('np', a, type(a))

1000
<class 'numpy.int32'>
<class 'int'>
np 1001 <class 'numpy.int32'>


А вот арифметические операции сохраняют NumPy-тип данных:

In [ ]:
a = np.int32(1000)
b = a + 25
print(b)
# 1025
print(type(b))
# <class 'numpy.int32'>

1025
<class 'numpy.int32'>


Примечание. В некоторых более старых версиях NumPy тип данных может измениться на int64 вместо ожидаемого int32. Это связано с тем, что число 25 может быть сначала преобразовано в NumPy-тип данных int (по умолчанию int64) перед сложением. Скорее всего, на практике вам не особо помешает такая особенность, однако о ней следует помнить, когда требуется хранить числа максимально оптимальным способом.

Если операция проводится с двумя NumPy-типами с фиксированным объёмом памяти, в результате сохраняется наиболее «старший» тип:

In [ ]:
a = np.int32(1000)
b = np.int8(25)
c = a + b
print(c)
# 1025
print(type(c))
# <class 'numpy.int32'>

1025
<class 'numpy.int32'>


ПЕРЕПОЛНЕНИЕ
Если же при арифметических операциях происходит переполнение максимально выделенной памяти для типа, возникает предупреждение.

In [ ]:
 a = np.int8(260)
 print(a)
 # В переменной a теперь оказалось число 4, а не 260. По сути в переменную записался остаток от деления 260 на 256, а не само число. Ошибка при этом не возникла.

4


Если же при арифметических операциях происходит переполнение максимально выделенной памяти для типа, возникает предупреждение.

In [ ]:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
# 2147483610 2147483605
print(a + b)
# -81
# RuntimeWarning: overflow encountered in int_scalars
# Переполнено int'овое значение



2147483610 2147483605
-81
4294967215


C:\Users\Konstantin\AppData\Local\Temp\ipykernel_14120\794910908.py:5: RuntimeWarning: overflow encountered in long_scalars
  print(a + b)


In [ ]:
#Чтобы избежать этой ошибки, вначале следовало преобразовать переменные к большему типу:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
print(np.int64(a) + np.int64(b))

2147483610 2147483605
4294967215


### Типы данных с плавающей точкой в NumPy

In [ ]:
import numpy as np
np.finfo(np.float16)
# finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)
np.finfo(np.float32)
# finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)
np.finfo(np.float64)
# finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)
#>>>>># np.finfo(np.float128)
# finfo(resolution=1e-18, min=-1.189731495357231765e+4932, max=1.189731495357231765e+4932, dtype=float128)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

Примечание. Если ввести в VS Code команду np.finfo(np.float128), ответом будет AttributeError: module 'numpy' has no attribute 'float128'. Всё потому, что numpy.float128 не поддерживается в Windows с использованием компилятора MS. Если вам всё же нужно поработать с numpy.float128, воспользуйтесь онлайн-IDE. https://www.online-python.com/


In [ ]:
print(np.float16(4.12))
# 4.12
print(np.float16(4.13))
# 4.13
print(np.float16(4.121))
# 4.12
print(np.float16(4.122))
# 4.12
print(np.float16(4.123))
# 4.12
print(np.float16(4.124))
# 4.125
print(np.float16(4.125))
# 4.125
print(np.float16(4.126))
# 4.125
print(np.float16(4.127))
# 4.13
print(np.float16(4.128))
# 4.13
print(np.float16(4.129))
# 4.13

4.12
4.13
4.12
4.12
4.12
4.125
4.125
4.125
4.13
4.13
4.13


Следует обратить внимание на типы данных bool_ и str_. Они аналогичны bool и str из встроенных в Python, однако записывать их необходимо именно с нижним подчёркиванием, иначе произойдёт приведение к стандартному типу данных, а не типу NumPy. В целом, существенной разницы между этими типами данных нет, однако о такой двойственности следует помнить при сравнении типов переменных: тип bool не является эквивалентным numpy.bool_, несмотря на то что оба типа данных хранят значения True или False.

In [ ]:
# bool_

a = True
print(type(a))
# <class 'bool'>
a = np.bool(a)
print(type(a))
# <class 'bool'>
a = np.bool_(a)
print(type(a))
# <class 'numpy.bool_'>
 
# Значения равны
print(np.bool(True) == np.bool_(True))
# True
# А типы — нет:
print(type(np.bool(True)) == type(np.bool_(True)))
# False


## Str_

a = "Hello world!"
print(type(a))
# <class 'str'>
a = np.str(a)
print(type(a))
# <class 'str'>
a = np.str_(a)
print(type(a))
# <class 'numpy.str_'>

<class 'bool'>
<class 'bool'>
<class 'numpy.bool_'>
True
False
<class 'str'>
<class 'str'>
<class 'numpy.str_'>


C:\Users\Konstantin\AppData\Local\Temp\ipykernel_14120\4280234698.py:6: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.bool(a)
C:\Users\Konstantin\AppData\Local\Temp\ipykernel_14120\4280234698.py:14: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(np.bool(True) == np.bool_(True))
C:\Users\Konstantin\AppData\Local\Temp\ipykernel_14120\4280

In [ ]:
import numpy as np
a = np.uint8(-456)
print(a)


56


## Массивы



Итак, массив — это структура данных, в которой:

1
Элементы хранятся в указанном порядке.

2
Каждый элемент можно получить по индексу за одинаковое время.

3
Все элементы приведены к одному и тому же типу данных.

4
Максимальное число элементов и объём выделенной памяти заданы заранее.

Размерностью массива называют то число индексов, которое необходимо для однозначного получения элемента из массива.

Форма (структура) массива — это информация о количестве размерностей массива и протяжённости массива по каждой из размерностей. Например, можно задать двумерный массив размера 3x5 — у этой таблицы две размерности: 3 строки и 5 столбцов.


Создание массива из списка

Создать массив из списка можно с помощью функции np.array(<объект>):

In [ ]:
import numpy as np
arr = np.array ([1,4,2,5,15])
print(arr)
print(type(arr))

[ 1  4  2  5 15]
<class 'numpy.ndarray'>


In [ ]:
# Перечислить список из списков можно
# было и в одну строку, но на нескольких
# строках получается нагляднее
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr
# array([[12, 45, 78],
#        [34, 56, 13],
#        [12, 98, 76]])



array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

Типы данных в массиве

Мы только что узнали, что массив — это набор однотипных данных, но не указали никакой тип. Какого типа данные хранятся теперь в массиве arr? Узнать это можно, напечатав свойство dtype:

In [ ]:
arr = np.array([1,4,2,5,15])
arr.dtype

dtype('int32')

Также тип данных можно будет указать или изменить позднее, если окажется, что текущий тип избыточен или, наоборот, недостаточен для хранения чисел с требуемой точностью. Однако числа в массиве всё равно будут одного и того же типа данных, даже если разработчик этого явно не указал.

In [ ]:
import numpy as np
# задать тип данных сразу при создании массива можно с помощью параметра dtype:
arr = np.array([1,5,124,9,10], dtype=np.int8)
arr # выведет вместе с типом данных
print(arr) # выведет лишь сам массив

arr[2] = 2000
print(arr)

arr[2] = 125.5
print(arr)

# строка с цифрами может быть преобразованна в инт
arr[2] = '12'
print(arr)

# строка с буквами не может быть преобразованна в интегер
# arr[2] = 'test'


# Поменять тип данных во всём массиве можно с помощью тех же функций, которыми мы пользовались для преобразования типов отдельных переменных в предыдущем юните 
# (например, np.int32 или np.float128): 
arr = np.float64(arr)
# float128 не работает на windows
print('128')
print(arr)

# При преобразовании типов данных в массиве не забывайте о том, что часть чисел может потерять смысл, 
# если менять тип данных с более ёмкого на менее ёмкий:
arr = np.array([12321, -1234, 3435, -214, 100], dtype=np.int32)
arr
# array([12321, -1234,  3435,  -214,   100], dtype=int32)
 
arr = np.uint8(arr)
arr

arr = np.array([345234, 876362.12, 0, -1000, 99999999], dtype=np.float64)
print(arr)

[  1   5 124   9  10]
[  1   5 -48   9  10]
[  1   5 125   9  10]
[ 1  5 12  9 10]
128
[ 1.  5. 12.  9. 10.]
[ 3.4523400e+05  8.7636212e+05  0.0000000e+00 -1.0000000e+03
  9.9999999e+07]


    ##Свойства NumPy-массивов

In [ ]:
import numpy as np
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr= np.array([
    [12,45,78],
    [34,56,13],
    [34,56,13],
    [12,98,76]
    ], dtype=np.int16)

# 1 Узнать размерность массива можно с помощью .ndim:


print(arr.ndim)
print(nd_arr.ndim)


# 2 Узнать общее число элементов в массиве можно с помощью .size:

print('size:', arr.size)
print('size:',nd_arr.size)

# 3 Форма или структура массива хранится в атрибуте .shape:

print('shape', arr.shape)
print('shape', nd_arr.shape)

# Форма массива хранится в виде кортежа с числом элементов, равным размерности массива. 
# Соответственно, для одномерного массива напечатан кортеж длины 1. 
# Обратите внимание, что для двумерного массива вначале было напечатано число «строк», а затем число «столбцов». 
# Это так только отчасти. На самом деле массив как бы состоит из внешних и внутренних массивов

# 4 узнать, сколько «весит» каждый элемент массива в байтах позволяет .itemsize

print('itemsize, (bytes):',arr.itemsize)
print('itemsize, (bytes):', nd_arr.itemsize)

1
2
size: 5
size: 12
shape (5,)
shape (4, 3)
itemsize, (bytes): 1
itemsize, (bytes): 2


### Заполнение новых массивов

Можно заранее подготовить массив заданной размерности, заполненный нулями, а потом загружать в него реальные данные по мере необходимости.

Массив из нулей создаётся функцией np.zeros. Она принимает аргументы shape (обязательный) — форма массива (одно число или кортеж) и dtype (необязательный) — тип данных, который будет храниться в массиве.

In [ ]:
import numpy as np
#   np.zeros(shape,dtype)

zeros_1d_a = np.zeros(5)
zeros_1d_a



array([0., 0., 0., 0., 0.])

In [ ]:
zeros_1d_b = np.zeros((5,),dtype=np.int8)
zeros_1d_b

array([0, 0, 0, 0, 0], dtype=int8)

In [ ]:
zeros_3d = np.zeros ((5,4,3),dtype=np.float32)
print(zeros_3d.shape)

(5, 4, 3)


Ещё одной удобной функцией для создания одномерных массивов является arange. Она аналогична встроенной функции range, но обладает рядом особенностей. 

        Вот её сигнатура: arange([start,] stop, [step,], dtype=None).

Аргументы start (по умолчанию 0), step (по умолчанию 1) и dtype (определяется автоматически) являются необязательными:

        start (входит в диапазон возвращаемых значений) задаёт начальное число;
        stop (не входит в диапазон возвращаемых значений, как и при использовании range) задаёт правую границу диапазона;
        step задаёт шаг, с которым в массив добавляются новые значения.
В отличие от range, в функции arange все перечисленные параметры могут иметь тип float.

In [ ]:
# массив из пяти чисел от 0 до 4:
np.arange(5) 

# Создадим массив от 2.5 до 5:
np.arange(2.5, 5)


array([2.5, 3.5, 4.5])

На самом деле операции с плавающей точкой не всегда бывают предсказуемыми из-за особенностей хранения таких чисел в памяти компьютера. Поэтому для работы с дробными параметрами start, stop и step лучше использовать функцию linspace (англ. linear space — линейное пространство). Она тоже возвращает одномерный массив из чисел, расположенных на равном удалении друг от друга между началом и концом диапазона, но обладает немного другим поведением и сигнатурой:

np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

        start и stop являются обязательными параметрами, задающими начало и конец возвращаемого диапазона;
        num — параметр, задающий число элементов, которое должно оказаться в массиве (по умолчанию 50);
        endpoint — включён или исключён конец диапазона (по умолчанию включён);
        retstep (по умолчанию False) позволяет указать, возвращать ли использованный шаг между значениями, помимо самого массива;
        dtype — уже хорошо знакомый нам параметр, задающий тип данных (если не задан, определяется автоматически).


In [ ]:
import numpy as np
arr = np.linspace (1, 2, 10)
print(arr)

# Создадим массив из десяти чисел между 1 и 2, не включая 2:
arr = np.linspace(1, 2, 10, endpoint=False)
print(arr)

# Узнаем, какой шаг был использован для создания массива из десяти чисел между 1 и 2, где 2 включалось и не включалось:

arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)
print(arr)

arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)

#Функцию linspace очень удобно использовать при построении графиков различных функций, 
# поскольку она позволяет получить равномерный массив чисел, 
# к которому можно применить исследуемую функцию и показать результат на графике.

arr, step = np.linspace (-6, 21, 60, endpoint=True, retstep=True)
print(step)

arr, step = np.linspace (-6, 21, 60, endpoint=False, retstep=True)
print(step)



[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
0.1111111111111111
[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
0.1
0.4576271186440678
0.45


## Действия с массивами

Изменение формы массива

In [ ]:
import numpy as np
arr = np.arange(8)
print(arr)

# Поменять форму массива arr можно с помощью присвоения атрибуту shape (строки, столбцы) кортежа с желаемой формой:
arr.shape = (2, 4)
print(arr)


[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


Как и принято в NumPy, первое число задало число строк, а второе — число столбцов.
Присвоение нового значения атрибуту shape изменяет тот массив, с которым производится действие.

Чтобы оставить исходный массив без изменений и дополнительно получить новый массив новой формы, нужно использовать функцию reshape. Она также принимает в качестве аргумента кортеж из чисел для формы, но возвращает новый массив, а не изменяет исходный:

In [ ]:
arr = np.arange(8)
arr_new = arr.reshape((2,4))
print(arr)
arr_new


[0 1 2 3 4 5 6 7]


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

У функции reshape есть дополнительный именованный аргумент order. Он задаёт принцип, по которому элементы заполняют массив новой формы. Если order='C' (по умолчанию), массив заполняется по строкам, как в примере выше. Если order='F', массив заполняется числами по столбцам:

In [ ]:
arr = np.arange(8)
arr_new = arr.reshape((2,4), order ='F')
arr_new


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Ещё одной часто используемой операцией с формой массива (особенно двумерного) является транспонирование. Эта операция меняет строки и столбцы массива местами. В NumPy эту операцию совершает функция transpose.

Будем работать с двумерным массивом:

In [ ]:
arr = np.arange(8)
arr.shape = (2,4)
print(arr)
print()
#Транспонируем его: .transpose()
arr_trans = arr.transpose()
print(arr_trans)

#При транспонировании одномерного массива его форма не меняется: 
# KD по сути одномерный массив не имеет понятий строки или столбца
print()
arr = np.arange(3)
print(arr.shape)
arr_trans = arr.transpose()
print()
print(arr_trans.shape)

[[0 1 2 3]
 [4 5 6 7]]

[[0 4]
 [1 5]
 [2 6]
 [3 7]]

(3,)

(3,)


## Индексы и срезы в массивах

In [ ]:
import numpy as np
arr = np.linspace(1, 2, 6)
print(arr)

# Обратиться к его элементу по индексу можно так же, как и к списку
arr[2]
print(arr[2])

# Привычная запись для срезов работает и для одномерных массивов:
print(arr[2:4])

# Наконец, напечатать массив в обратном порядке можно с помощью привычной конструкции [::-1]:
print(arr[::-1])



[1.  1.2 1.4 1.6 1.8 2. ]
1.4
[1.4 1.6]
[2.  1.8 1.6 1.4 1.2 1. ]


Многомерные масивы

In [ ]:
nd_array = np.linspace(0, 6, 12)
print(nd_array)

nd_array = np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
print(nd_array)

# Можно воспользоваться привычной записью нескольких индексов в нескольких квадратных скобках:
print(nd_array[1][2]) # 1 row, 2nd element (2 and 3 actually)

# Мы бы так и делали, если бы приходилось работать со списком из списков. 
# Однако проводить индексацию по массиву в NumPy можно проще: 
# достаточно в одних и тех же квадратных скобках перечислить индексы через запятую. Вот так:

print()
print('element [1,2] :')
print(nd_array[1,2])

# Также через запятую можно передавать срезы или даже их комбинации с индексами. 
# Например, получим все элементы из колонки 3 для первых двух строк:

print()
print('срез [:2, 2] :')
print(nd_array[:2,2])
# Несмотря на то что в массиве этот срез является столбцом, вместо него мы получили одномерный массив в виде строки.

#Можно применять срезы сразу и к строкам, и к столбцам:
print()
print('срез [1:, 2:4] :') # rows 1 and 2, columns 2 and 3
print(nd_array[1:,2:4])

# Чтобы получить все значения из какой-то оси, можно оставить на её месте двоеточие. 
# Например, из всех строк получим срез с третьего по четвёртый столбцы:
print()
print('срез [:, 2:4] :') # all rows (0, 1, 2), columns 2 and 3
print(nd_array[:, 2:4])

# Чтобы получить самую последнюю ось (в данном случае все столбцы), двоеточие писать необязательно.
# Строки будут получены целиком по умолчанию:
print()
print('срез [:2] :') # rows 0 and 1, all columns
print(nd_array[:2])



[0.         0.54545455 1.09090909 1.63636364 2.18181818 2.72727273
 3.27272727 3.81818182 4.36363636 4.90909091 5.45454545 6.        ]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
3.0

element [1,2] :
3.0

срез [:2, 2] :
[1. 3.]

срез [1:, 2:4] :
[[3.  3.5]
 [5.  5.5]]

срез [:, 2:4] :
[[1.  1.5]
 [3.  3.5]
 [5.  5.5]]

срез [:2] :
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]]


Задание 7.2

In [ ]:
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)

print(mystery.size)
print(mystery.shape) # 6 rows, 7 columns
print(mystery)

# 1 В переменную elem_5_3 сохраните элемент из 5 строки и 3 столбца
elem_5_3 = mystery[4,2]
print(elem_5_3)

# 2 В переменную last сохраните элемент из последней строки последнего столбца
last = mystery[5,6]
print()
print(last)

# 3 В переменную line_4 сохраните строку 4
print()
print('line_4')
line_4 = mystery[3:4] # not correct
print(line_4)
line_4 = mystery[3] # correct
print(line_4)

# 4 В переменную col_2 сохраните предпоследний столбец
col_2 = mystery[:,5]
print()
print(col_2)

# 5 Из строк 2-4 (включительно) получите столбцы 3-5 (включительно). 
# Результат сохраните в переменную part
part = mystery [1:4, 2:5]
print()
print(part)

print()
# 6 Сохраните в переменную rev последний столбец в обратном порядке ??????
rev = mystery[::-1,-1]
print()
print(rev)

# 7 Сохраните в переменную trans транспонированный массив
trans = mystery.transpose()
print()
print(trans)

42
(6, 7)
[[-13586  15203  28445 -27117  -1781 -17182 -18049]
 [ 25936 -30968  -1297  -4593   6451  15790   7181]
 [ 13348  28049  28655  -6012  21762  25397   8225]
 [ 13240   7994  32592  20149  13754  11795   -564]
 [-21725  -8681  30305  22260 -17918  12578  29943]
 [-16841 -25392 -17278  11740   5916    -47 -32037]]
30305

-32037

line_4
[[13240  7994 32592 20149 13754 11795  -564]]
[13240  7994 32592 20149 13754 11795  -564]

[-17182  15790  25397  11795  12578    -47]

[[-1297 -4593  6451]
 [28655 -6012 21762]
 [32592 20149 13754]]


[-32037  29943   -564   8225   7181 -18049]

[[-13586  25936  13348  13240 -21725 -16841]
 [ 15203 -30968  28049   7994  -8681 -25392]
 [ 28445  -1297  28655  32592  30305 -17278]
 [-27117  -4593  -6012  20149  22260  11740]
 [ -1781   6451  21762  13754 -17918   5916]
 [-17182  15790  25397  11795  12578    -47]
 [-18049   7181   8225   -564  29943 -32037]]


        # Сортировка одномерных массивов

Иногда возникает задача по сортировке значений в массиве. Для её решения существуют встроенная в NumPy функция sort. Применять функцию можно двумя способами.

Способ 1. Функция np.sort(<массив>) возвращает новый отсортированный массив:


In [ ]:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
# [23 12 45 12 23  4 15  3]
print(arr_new)
# [ 3  4 12 12 15 23 23 45]


[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


Способ 2. Функция <массив>.sort() сортирует исходный массив и возвращает None:

In [ ]:
arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
#None
print(arr)
#[ 3  4 12 12 15 23 23 45]


None
[ 3  4 12 12 15 23 23 45]


        Работа с пропущенными данными

In [ ]:
data = np.array([4, 9, -4, 3, -5])
# Воспользуемся встроенной в NumPy функцией sqrt, чтобы посчитать квадратные корни из элементов.
roots = np.sqrt(data)
print(roots)



[2.         3.                nan 1.73205081        nan]


C:\Users\Konstantin\AppData\Local\Temp\ipykernel_29560\1811888191.py:3: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


NumPy выдал предупреждение о том, что в функцию sqrt попало некорректное значение. Это было число -4, а как вы помните, корень из отрицательного числа в действительных числах не берётся. Однако программа не сломалась окончательно, а продолжила работу. На том месте, где должен был оказаться корень из -4, теперь присутствует объект nan. Он расшифровывается как Not a number (не число). Этот объект аналогичен встроенному типу None, но имеет несколько отличий:

    Отличие 1. None является отдельным объектом типа NoneType. np.nan — это отдельный представитель класса float:

In [ ]:
print(type(None))
# <class 'NoneType'>
print(type(np.nan))
# <class 'float'>
type(np.nan)

<class 'NoneType'>
<class 'float'>


float

    Отличие 2. None могут быть равны друг другу, а np.nan — нет:

In [ ]:
print(None == None)
# True
print(np.nan == np.nan)
# False

True
False


Как вы помните, чтобы грамотно сравнить что-либо с None, необходимо использовать оператор is. Это ещё более актуально для np.nan. Однако None даже через is не является эквивалентным np.nan:

In [ ]:
print(None is None)
# True
print(np.nan is np.nan)
# True
print(np.nan is None)
# False

True
True
False


Иногда работать с отсутствующими данными всё же нужно. Они могут возникнуть не только потому, что мы применили функцию к некорректному аргументу. Например, при анализе вакансий на сайте для некоторых из них может быть не указана зарплата, но при этом нам необходимо проанализировать статистику по зарплатам на сайте. Если попробовать посчитать сумму массива, который содержит np.nan, в итоге получится nan:


In [ ]:
sum(roots)
# nan

nan

Можно заполнить пропущенные значения, например, нулями. Для этого с помощью функции np.isnan(<массив>) узнаем, на каких местах в массиве находятся «не числа»:


In [197]:
np.isnan(roots)
# array([False, False,  True, False])

array([False, False,  True, False,  True])

Можно использовать полученный массив из True и False для извлечения элементов из массива roots, на месте которых в булевом массиве указано True. Таким способом можно узнать сами элементы, которые удовлетворяют условию np.isnan:


In [151]:
roots[np.isnan(roots)] # т е  np.isnan(roots) указывает индексы в массиве, всех isnan елементов
# array([nan])

array([nan, nan])

Этим элементам можно присвоить новые значения, например 0:

In [198]:
roots[np.isnan(roots)] = 0
sum(roots)

6.732050807568877

Ранее проблема при подсчёте суммы элементов в массиве roots возникала из-за того, что отсутствовало значение для квадратного корня из -4 — вместо него было указано np.nan. Сумма элементов массива, содержащего nan, также является nan. Поэтому приходится заменить nan, например, на 0, чтобы подсчитать сумму элементов массива.

In [199]:
np.isnan(np.nan)

True

# Задание 7.4 


    Получите булевый массив nans_index с информацией о np.nan в массиве mystery: True - значение пропущено, False - значение не пропущено
    В переменную `n_nan сохраните число пропущенных значений
    Скопируйте массив mystery в массив mystery_new. Заполните пропущенные значения в массиве mystery_new нулями
    Поменяйте тип данных в массиве mystery на int32 и сохраните в переменную mystery_int
    Отсортируйте значения в массиве по возрастанию и сохраните результат в переменную array
    Сохраните в массив table двухмерный массив, полученный из массива array. В нём должно быть 5 строк и 3 столбца. Причём порядок заполнения должен быть по столбцам!



In [236]:
import numpy as np
mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)

print(mystery.shape)

# 1 Получите булевый массив nans_index с информацией о np.nan в массиве mystery: True - значение пропущено, False - значение не пропущено

nans_index = np.isnan(mystery)
print(nans_index)

# 2 В переменную `n_nan сохраните число пропущенных значений
print()
print('2')
n_nan = sum(nans_index)
print(n_nan)

# 3 Скопируйте массив mystery в массив mystery_new. Заполните пропущенные значения в массиве mystery_new нулями

print()
print('3')
mystery_new = mystery.copy()
# without .COPY it will alternate original array
mystery_new[np.isnan(mystery_new)]= 0
print(mystery)
print(mystery_new)

# 4 Поменяйте тип данных в массиве mystery на int32 и сохраните в переменную mystery_int
print()
print('4')
mystery_int = np.int32(mystery)
print(mystery_int)

# 5 Отсортируйте значения в массиве по возрастанию и сохраните результат в переменную array
print()
print('5')
print(mystery)
array = np.sort(mystery)
print(array)

# 6 Сохраните в массив table двухмерный массив, полученный из массива array. В нём должно быть 5 строк и 3 столбца. Причём порядок заполнения должен быть по столбцам!
print()
print('6')
table = array.reshape((5,3), order ='F')
print(table)



# 7 Сохраните в переменную col средний столбец из table
# col = table[:,1:2]
print()
print('7')
col = table[:, 1]
print(col)

(15,)
[False False False  True False False False False  True False False False
  True False False]

2
3

3
[ 12279. -26024.  28745.     nan  31244.  -2365.  -6974.  -9212.     nan
 -17722.  16132.  25933.     nan -16431.  29810.]
[ 12279. -26024.  28745.      0.  31244.  -2365.  -6974.  -9212.      0.
 -17722.  16132.  25933.      0. -16431.  29810.]

4
[      12279      -26024       28745 -2147483648       31244       -2365
       -6974       -9212 -2147483648      -17722       16132       25933
 -2147483648      -16431       29810]

5
[ 12279. -26024.  28745.     nan  31244.  -2365.  -6974.  -9212.     nan
 -17722.  16132.  25933.     nan -16431.  29810.]
[-26024. -17722. -16431.  -9212.  -6974.  -2365.  12279.  16132.  25933.
  28745.  29810.  31244.     nan     nan     nan]

6
[[-26024.  -2365.  29810.]
 [-17722.  12279.  31244.]
 [-16431.  16132.     nan]
 [ -9212.  25933.     nan]
 [ -6974.  28745.     nan]]

7
[-2365. 12279. 16132. 25933. 28745.]


Ожидаемый ответ:

[[-26024.  -2365.  29810.]
 [-17722.  12279.  31244.]
 [-16431.  16132.     nan]
 [ -9212.  25933.     nan]
 [ -6974.  28745.     nan]]

Ваш ответ:

[[ 12279.  -2365.  16132.]
 [-26024.  -6974.  25933.]
 [ 28745.  -9212.      0.]
 [     0.      0. -16431.]
 [ 31244. -17722.  29810.]]